// sources/angular-app/src/app/post-card/post-card.component.ts
import { Component, Input, OnInit } from '@angular/core';
import Utils from '../utils';

export const
  PORTRAIT = 'portrait',
  LANDSCAPE = 'landscape',
  LANDSCAPE_COMPRESSED = 'landscapeCompressed',
  IMAGE_BACKGROUND = 'imageBackground';

@Component({
  selector: 'app-post-card',
  templateUrl: './post-card.component.html',
  styleUrls: ['./post-card.component.scss']
})
export class PostCardComponent implements OnInit {
  @Input() tags = '';
  @Input() model;
  @Input() showBlurb = false;
  @Input() format = PORTRAIT;
  @Input() classes;
  @Input() numOfComments;
  public mainImage_s;
  public blurb_t;
  public headline_s;
  public dateModified;
  public type;
  public authorAvatarUrl;
  public authorName;
  public slug;

  constructor() {
  }

  ngOnInit(): void {
    this.type = this.format;
    this.mainImage_s = this.model.mainImage_s;
    this.headline_s = this.model.headline_s;
    this.dateModified = Utils.formatDate(this.model.craftercms.dateModified);
    this.blurb_t = this.model.blurb_t;
    this.authorAvatarUrl = this.model.authorBio_o[0].profilePic_s;
    this.authorName = this.model.authorBio_o[0].name_s;
    this.slug = Utils.computeSlug(this.model.craftercms.path);
  }

}

<div [ngSwitch]="type">
  <div
    *ngSwitchCase="'imageBackground'"
    [ngStyle]="{ 'background-image': 'url(' + mainImage_s + ')'}"
    class="a-block d-flex align-items-center {{classes?.root}}"
  >
    <a class="text {{classes?.innerWrapper}}" routerLink="{{slug}}">
      <div class="post-meta">
        <span *ngIf="tags" class="category">{{tags}}</span>
        <span *ngIf="tags"> • </span>
        <span class="mr-2">{{dateModified}}</span>
        <span *ngIf="numOfComments"> • </span>
        <span *ngIf="numOfComments" class="ml-2">
          <span class="fa fa-comments"></span>{{numOfComments}}
        </span>
      </div>
      <h3>{{headline_s}}</h3>
      <p *ngIf="showBlurb">{{blurb_t}}</p>
    </a>
  </div>
  <a *ngSwitchCase="'portrait'" class="blog-entry {{classes?.root}}" routerLink="{{slug}}">
    <img src="{{mainImage_s}}">
    <div class="blog-content-body">
      <div class="post-meta">
        <span class="author mr-2">
          <img src="{{authorAvatarUrl}}">
          {{authorName}}
        </span>
        <span> • </span>
        <span class="mr-2">{{dateModified}}</span>
        <span *ngIf="numOfComments"> • </span>
        <span *ngIf="numOfComments" class="ml-2">
          <span class="fa fa-comments"></span>{{numOfComments}}
        </span>
      </div>
      <h2>{{headline_s}}</h2>
    </div>
  </a>
  <a *ngSwitchCase="'landscapeCompressed'" class="{{classes?.root}}" routerLink="{{slug}}">
    <img class="mr-4" src="{{mainImage_s}}">
    <div class="text">
      <h4>{{headline_s}}</h4>
      <div class="post-meta">
        <span class="mr-2">{{dateModified}}</span>
      </div>
    </div>
  </a>
  <div *ngSwitchCase="'landscape'" class="post-entry-horizontal">
    <a class="{{classes?.root}}" routerLink="{{slug}}">
      <div [ngStyle]="{ 'background-image': 'url(' + mainImage_s + ')'}" class="image"></div>
      <span class="text">
        <div class="post-meta">
          <span class="author mr-2">
            <img src="{{authorAvatarUrl}}">
            {{authorName}}
          </span>
          <span> • </span>
          <span class="mr-2">{{dateModified}}</span>
          <span *ngIf="numOfComments"> • </span>
          <span *ngIf="numOfComments" class="ml-2">
            <span class="fa fa-comments"></span>{{numOfComments}}
          </span>
        </div>
        <h2>{{headline_s}}</h2>
      </span>
    </a>
  </div>
  <div *ngSwitchDefault>no view</div>
</div>

// sources/react-app/src/shared/PostCard.js
/*
 * Copyright (C) 2007-2020 Crafter Software Corporation. All Rights Reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3 as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import React from 'react';
import { Link } from 'react-router-dom';
import { useIntl } from 'react-intl';
import { Field, RenderField } from '@craftercms/studio-guest';

export const
  PORTRAIT = 'portrait',
  LANDSCAPE = 'landscape',
  LANDSCAPE_COMPRESSED = 'landscapeCompressed',
  IMAGE_BACKGROUND = 'imageBackground';

function PostCard(props) {
  const { formatDate } = useIntl();
  const {
    classes,
    format = PORTRAIT,
    showBlurb = false,
    numOfComments,
    model,
    model: {
      authorBio_o: [{
        name_s: authorName,
        profilePic_s: authorAvatarUrl
      }],
      headline_s,
      mainImage_s,
      mainImageAlt_s = '',
      categories_o,
      craftercms: {
        dateModified
      }
    }
  } = props;
  const slug = computeSlug(model.craftercms.path);
  switch (format) {
    case PORTRAIT:
      return (
        <Field
          component={Link}
          model={model}
          to={slug}
          className={`blog-entry ${classes?.root ?? ''}`}
        >
          <div className="img-container">
            <RenderField component="img" model={model} target="src" fieldId="mainImage_s" alt={mainImageAlt_s} />
          </div>
          <div className="blog-content-body">
            <div className="post-meta">
              <Field
                component="span"
                model={model}
                fieldId="authorBio_o"
                index={0}
                className="author mr-2"
              >
                <img src={authorAvatarUrl} alt="" /> {authorName}
              </Field>
              {' • '}<span className="mr-2">{formatDate(dateModified)}</span>
              {
                numOfComments &&
                <>
                  {' • '}<span className="ml-2"><span className="fa fa-comments" /> {numOfComments}
                </span>
                </>
              }
            </div>
            <RenderField component="h2" model={model} fieldId="headline_s" />
          </div>
        </Field>
      );
    case LANDSCAPE:
      return (
        <div className="post-entry-horizontal">
          {/* Notice: Adding the ICE to the above element wouldn't stop
              the link from navigating when clicked */}
          <Field component={Link} model={model} to={slug} className={classes?.root}>
            <RenderField
              model={model}
              fieldId="mainImage_s"
              target="style.backgroundImage"
              format={(src) => `url(${src})`}
              className="image"
            />
            <span className="text">
              <div className="post-meta">
                <Field className="author mr-2" model={model} fieldId="authorBio_o" index={0}>
                  <img src={authorAvatarUrl} alt={mainImageAlt_s} /> {authorName}
                </Field>
                • <span className="mr-2">{formatDate(dateModified)}</span>
                {
                  numOfComments &&
                  <>
                    • <span className="ml-2"><span className="fa fa-comments" /> ${numOfComments}</span>
                  </>
                }
              </div>
              <RenderField component="h2" fieldId="headline_s" model={model} />
            </span>
          </Field>
        </div>
      );
    case LANDSCAPE_COMPRESSED:
      return (
        <Field component={Link} model={model} to={slug} className={classes?.root}>
          <RenderField
            component="img"
            target="src"
            model={model}
            fieldId="mainImage_s"
            className="mr-4"
            alt=""
          />
          <div className="text">
            <RenderField component="h4" model={model} fieldId="headline_s" />
            <div className="post-meta">
              <span className="mr-2">{formatDate(dateModified)}</span>
            </div>
          </div>
        </Field>
      );
    case IMAGE_BACKGROUND:
      return (
        <Field
          model={model}
          fieldId="mainImage_s"
          className={`a-block d-flex align-items-center ${classes?.root ?? ''}`}
          style={{ backgroundImage: `url(${mainImage_s})` }}
        >
          <Field
            component={Link}
            model={model}
            to={slug}
            className={`text ${classes?.innerWrapper}`}
          >
            <div className="post-meta">
              {
                categories_o &&
                <>
                  {
                    categories_o?.map(category =>
                      <span className="category" key={category.key}>{category.value_smv}</span>
                    )
                  }

                  {' • '}
                </>
              }
              <span className="mr-2">{formatDate(dateModified)}</span>
              {
                numOfComments &&
                <>
                  {' • '}<span className="ml-2"><span className="fa fa-comments" /> {numOfComments}
                </span>
                </>
              }
            </div>
            <RenderField component="h3" model={model} fieldId="headline_s" />
            {
              showBlurb && <RenderField component="p" model={model} fieldId="blurb_t" />
            }
          </Field>
        </Field>
      );
    default:
      console.error(`Unknown PostCard format "${format}" on post "${headline_s}"`);
      return (
        <Field component={Link} model={model} to={slug} className={classes?.root}>
          <h2>{headline_s}</h2>
        </Field>
      );
  }
}

function computeSlug(path) {
  return path
    .replace(/(\/site\/components)|(index\.xml)/g, '')
    .replace(/(\/site\/website)|(index\.xml)/g, '')
    .replace(/(\/\/)/g, '/')
    .replace('.xml', '');
}

export default PostCard;
